default: DoubleQueueDriver.java
	     javac com/Gradescope/DoubleQueue/code/DoubleQueueDriver.java

run:  DoubleQueueDriver.class
	  java com.Gradescope.DoubleQueue.code.DoubleQueueDriver

clean: rm -f *.class